# =============================================
# Jekyll configuration
# =============================================

# Where things are
source:           ./source
destination:      ./build
layouts_dir:      _jekyll/_layouts
includes_dir:     _jekyll/_includes
data_dir:         _jekyll/_data
plugins_dir:      _jekyll/_plugins
collections:
  beauty:
    output:       true
  filmography:
    output:       true
  schedule:
    output:       true
  press:
    output:       true

# Outputting
permalink:        pretty
defaults:
  - scope:
      type:       pages
    values:
      layout:     base
  - scope:
      type:       beauty
    values:
      layout:     post-beauty
  - scope:
      type:       filmography
    values:
      layout:     post-filmography
  - scope:
      type:       schedule
    values:
      layout:     post-schedule
  - scope:
      type:       press
    values:
      layout:     post-press

# Plugins
assets:
  cache:          false
  sources:
                  - _assets/javascripts
                  - _assets/stylesheets
                  - _assets/images
                  - _assets/uploads

# =============================================
# Site metadata
# =============================================

# General
title:            Selena Lee Official Website
url:              http://selena-lee.com
since:            2006

# Accounts
analytics:        UA-12048611-1
selena:
  facebook:       selenaleelalee
  instagram:      selenaleelalee
  youtube:        selenabeautytips
  weibo:          1731864915
  tencent:        selenaliszewan
fanclub:
  twitter:        selenalicom
  instagram:      selenaleeofficial
  vimeo:          selenalicom
  weibo:          selenaliofficial
  tencent:        selenaliofficial